[package]
name = "vscode-remote-try-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "abc161",
  "abc163",
  "abc172",
  "abc176",
  "abc182",
  "abc184",
  "abc186",
  "practice",
]
exclude = []

[dependencies]
