[package]
name = "vscode-remote-try-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "abc152",
  "abc161",
  "abc163",
  "abc164",
  "abc165",
  "abc168",
  "abc170",
  "abc172",
  "abc174",
  "abc176",
  "abc177",
  "abc178",
  "abc181",
  "abc182",
  "abc183",
  "abc184",
  "abc185",
  "abc186",
  "practice",
]
exclude = []

[dependencies]
