[package]
name = "vscode-remote-try-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "abc001",
  "abc002",
  "abc003",
  "abc004",
  "abc005",
  "abc006",
  "abc007",
  "abc009",
  "abc010",
  "abc011",
  "abc012",
  "abc013",
  "abc014",
  "abc015",
  "abc016",
  "abc017",
  "abc018",
  "abc019",
  "abc020",
  "abc021",
  "abc022",
  "abc023",
  "abc024",
  "abc025",
  "abc026",
  "abc027",
  "abc028",
  "abc029",
  "abc030",
  "abc031",
  "abc032",
  "abc033",
  "abc034",
  "abc035",
  "abc036",
  "abc037",
  "abc038",
  "abc043",
  "abc044",
  "abc045",
  "abc048",
  "abc062",
  "abc065",
  "abc085",
  "abc103",
  "abc109",
  "abc148",
  "abc152",
  "abc160",
  "abc161",
  "abc163",
  "abc164",
  "abc165",
  "abc166",
  "abc168",
  "abc170",
  "abc171",
  "abc172",
  "abc174",
  "abc175",
  "abc176",
  "abc177",
  "abc178",
  "abc179",
  "abc180",
  "abc181",
  "abc182",
  "abc183",
  "abc184",
  "abc185",
  "abc186",
  "abc192",
  "abc214",
  "abc215",
  "abc226",
  "abc259",
  "abc261",
  "abc291",
  "abc333",
  "practice",
]
exclude = []

[dependencies]
